site_name: 'Server for Symfony Flex'
repo_url: 'https://github.com/moay/server-for-symfony-flex'
repo_name: 'moay/server-for-symfony-flex'
pages:
    - 'Introduction': 'index.md'
    - 'Requirements': 'topics/prerequisites.md'
    - 'Setup': 'topics/setup.md'
    - 'Configuration': 'topics/configuration.md'
    - 'Updating recipes': 'topics/recipe_updating.md'
    - 'About recipes': 'topics/recipes.md'
    - 'Commands': 'topics/commands.md'
theme:
    name: 'material'
    palette:
        primary: 'grey'
